apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres-logmonitor
    access: proxy
    url: postgres:5432
    database: logmonitor
    user: logmonitor
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: logmonitor
